version: '3'
services:
  storage-service:
    container_name: "storage-service"
    build:
      context: storage-service
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
  adminstration-service:
    build:
      context: administration-service
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
  repair-service:
    build:
      context: repair-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "storage-service"
  repair-parts-service:
    build:
      context: repair-parts-service
      dockerfile: Dockerfile
    ports:
      - "8182:8182"
  document-service:
    build:
      context: document-service
      dockerfile: Dockerfile
    ports:
      - "8899:8899"
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
#    container_name: "elasticsearch"
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false

